import Head from 'next/head';
import { useState } from 'react';

import Image from 'next/image';
import devEdWave from '../public/dev-ed-wave.png';
import mobile from '../public/smartphone.png';
import code from '../public/code.png';
import Navbar from '../components/Navbar';
import SocialIcons from '../components/SocialIcons';

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Kerolos Tawfik Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40'>
        <section className='min-h-screen'>
          <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
          <div className='text-center p-8'>
            <h2 className='text-5xl py-2 text-teal-600 font-bold dark:text-teal-400 md:text-6xl'>
              Kerolos Tawfik
            </h2>
            <h3 className='text-2xl py-2 dark:text-white md:text-3xl'>
              Junior Mobile Application Developer
            </h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl'>
              {' '}
              Freelancer/Full-time Mobile Application Developer native and
              cross-platform . Join me down below and lets get cracking!
            </p>
            <SocialIcons />
          </div>
          <div className='relative mx-auto mt-20 bg-gradient-to-b from-teal-500 h-80 w-80 rounded-full overflow-hidden md:h-96 md:w-96'>
            <Image src={devEdWave} fill objectFit='fit' alt='icon' />
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-5 dark:text-white'>Who I am</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              {' '}
              Certified Mobile App Developer with total of{' '}
              <span className='text-teal-500'> 1 Year of experience </span>
              in Android native with Jave, Xamarin, Flutter and React Native I
              have{' '}
              <span
                className='text-teal-500'
                onClick={() =>
                  window.open('https://confirm.udacity.com/GFQFQEP9', '_blank')
                }
              >
                Nanodgree Certification
              </span>{' '}
              in Android native then I took Developer Certification in Xamarin
              from Xamarin university. now I learning and working with React
              Native.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              I offer from a wide range of services, including designing and
              programming.
            </p>
          </div>
          <div className='lg:flex gap-10 text-center'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image
                className='mx-auto'
                src={mobile}
                width={100}
                height={100}
                alt='mobile'
              />
              <h3 className='text-lg font-medium pt-8 pb-2'>Mobile Service</h3>
              <p className='py-2'>
                Creating elegant mobile apps suited for your needs.
              </p>
              <h4 className='py-4 text-teal-600'>Platform I Use</h4>
              <p className='text-gray-800 py-1'>Native Android</p>
              <p className='text-gray-800 py-1'>Flutter</p>
              <p className='text-gray-800 py-1'>Xamarin</p>
              <p className='text-gray-800 py-1'>React Native</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
