import Head from 'next/head';
import { useState } from 'react';
import Navbar from '../components/Navbar';
import SocialIcons from '../components/SocialIcons';
const skills = ['Next.js', 'Node.js', 'TypeScript', 'React Native', 'AWS', 'Firebase', 'Flutter', 'Java / Kotlin', 'Xamarin.Forms', 'Git', 'Jira'];
export default function Home() {
 const [darkMode, setDarkMode] = useState(true);
 return <div className={darkMode ? 'portfolio dark-theme' : 'portfolio light-theme'}>
 <Head><title>Kerolos Fawzy | Full-Stack & Mobile Developer</title><meta name="description" content="Kerolos Fawzy, full-stack and mobile developer in Cairo. Next.js dashboards, Node.js backends, and React Native apps. Explore projects and resume."/><meta name="viewport" content="width=device-width, initial-scale=1"/><meta property="og:title" content="Kerolos Fawzy | Full-Stack Developer"/><meta property="og:description" content="Next.js dashboards, Node.js backends, and mobile apps. Explore my work and get in touch."/><link rel="icon" href="/favicon.ico"/></Head>
 <a className="skip-link" href="#main">Skip to content</a><div className="page-shell"><Navbar darkMode={darkMode} setDarkMode={setDarkMode}/><main id="main">
 <section className="hero" aria-labelledby="hero-title"><div><p className="eyebrow"><span className="status-dot"/> CAIRO, EGYPT · FULL-STACK & MOBILE</p><h1 id="hero-title">Building the web.<br/><span>Connecting the dots.</span></h1><p className="hero-intro">I’m Kerolos Fawzy, a <strong>Full-Stack Developer</strong> working with Next.js and Node.js. I build admin dashboards, backend services, and mobile apps that bring everyday workflows together.</p><div className="actions"><a className="button primary" href="#work">Explore my work ↗</a><a className="button secondary" href="mailto:kerolosfawzy1997@gmail.com">Let’s talk →</a></div><SocialIcons/></div>
 <div className="architecture" aria-label="My development stack"><div className="panel-bar"><span>● ● ●</span><small>FROM INTERFACE TO INFRASTRUCTURE</small></div><div className="stack-label">MY DEVELOPMENT STACK</div>{[['N','Next.js + TypeScript','Dashboards & web interfaces'],['{ }','Node.js + AWS','Backend services & storage'],['R','React Native','Connected mobile experiences']].map((item,i)=><div key={item[0]}>{i>0 && <div className="connector" aria-hidden="true">↓</div>}<div className="stack-card"><span className="stack-icon">{item[0]}</span><div><strong>{item[1]}</strong><p>{item[2]}</p></div><span className="stack-number">0{i+1}</span></div></div>)}<div className="panel-footer"><span className="status-dot"/> One connected experience.</div></div></section>
 <div className="skill-strip"><span>TOOLS I WORK WITH</span><p>Next.js <b>/</b> Node.js <b>/</b> TypeScript <b>/</b> React Native <b>/</b> AWS</p></div>
 <section id="work" className="section"><div className="section-heading"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Built around real needs.</h2></div><p>Scheduling, attendance, and operations.<br/>Web and mobile working together.</p></div><article className="featured-project"><div className="project-art"><span className="art-kicker">FEATURED PROJECT / HEALTHCARE</span><div className="art-title">DocMoonLight<span>Mobile app + admin dashboard</span></div><div className="art-modules"><span>Shift scheduling</span><span>Attendance</span><span>Admin oversight</span></div><span className="art-caption">Next.js ↔ Node.js ↔ React Native</span></div><div className="project-copy"><p className="eyebrow">FULL-STACK DEVELOPMENT</p><h3>From doctors’ shifts to admin control.</h3><p>Developed a React Native app to streamline doctors’ shift scheduling and attendance, alongside a Next.js dashboard built with TypeScript for administrative control and oversight.</p><ul><li>Node.js and AWS infrastructure for application operation and storage.</li><li>Mobile interfaces with tables, maps, and calendars.</li><li>Stripe payment integration and Zoom video calls.</li></ul><div className="tags">{['Next.js','TypeScript','Node.js','AWS','React Native'].map(s=><span key={s}>{s}</span>)}</div></div></article>
 <div className="project-grid"><article className="project-card"><span className="project-index">02 / ATTENDANCE</span><h3>Zacks</h3><p>A Flutter application for employee attendance, with location-based clock-in and clock-out using Google Maps. Firebase supports the database and authentication.</p><div className="tags"><span>Flutter</span><span>Firebase</span><span>Google Maps API</span></div><p className="project-date">Freelance project · May–September 2020</p></article><article className="project-card"><span className="project-index">03 / SITE OPERATIONS</span><h3>IDEX</h3><p>A mobile application for managing cleaning inspections at large sites. Built custom view renderers, list filtering and sorting, and applied MVVM with performance profiling.</p><div className="tags"><span>Xamarin</span><span>MVVM</span><span>Performance profiling</span></div><p className="project-date">CrossWorkers internship · July–September 2018</p></article></div></section>
 <section id="about" className="section about-grid"><div><p className="eyebrow">02 / ABOUT ME</p><h2>A mobile foundation.<br/><span className="muted">A full-stack perspective.</span></h2><p className="body-copy">My background spans native Android and cross-platform mobile development. My work also includes Next.js dashboards and Node.js backends, connecting user-facing applications with the systems behind them.</p><p className="body-copy">I studied Computer Science at Helwan University and enjoy turning practical challenges into clear, useful software.</p><div className="tags skill-tags">{skills.map(s=><span key={s}>{s}</span>)}</div></div><div className="credentials"><div><span className="credential-label">EXPERIENCE</span><h3>DocMoonLight</h3><p>React Native Developer · from August 2022</p><p>Contributions across the mobile app, admin dashboard, and backend.</p></div><div><span className="credential-label">EDUCATION</span><h3>BSc in Computer Science</h3><p>Helwan University, Egypt · 2015–2020</p></div><div><span className="credential-label">CERTIFICATIONS</span><h3>Android & cross-platform development</h3><p>NTL / Udacity Android Nanodegree · 2017</p><p>Xamarin Certified Mobile Developer · 2018</p></div><div><span className="credential-label">LANGUAGES</span><p>Arabic · Native / English · Very good / German · Fair</p></div></div></section>
 <section id="contact" className="contact-section"><p className="eyebrow">03 / GET IN TOUCH</p><h2>Have something<br/><span>in mind?</span></h2><p>Let’s talk about your next dashboard, web platform, or mobile app.</p><a className="email-link" href="mailto:kerolosfawzy1997@gmail.com">kerolosfawzy1997@gmail.com <span aria-hidden="true">↗</span></a><div className="contact-links"><a href="tel:+201285665759">+20 128 566 5759</a><a href="/Kerolos_Fawzy_cv.pdf" target="_blank" rel="noopener noreferrer">View my resume ↗</a></div></section></main><footer><span>© {new Date().getFullYear()} Kerolos Fawzy</span><span>Full-stack thinking. Thoughtful execution.</span><a href="#main">Back to top ↑</a></footer></div></div>;
}
